### ISSUE TITLE
What do the symbols in the gutter mean?

### ISSUE THREAD

**Issue by jfilter** [fcannizzaro/npm-install#2]
![screen shot 2017-07-12 at 20 01 10](https://user-images.githubusercontent.com/3450307/28132375-fb0e7ef4-673c-11e7-8757-e3fa3920e983.png)

**Comment by fcannizzaro** [comment]
See here ([icons table](https://github.com/fcannizzaro/npm-install#icons))

**Local Imports** fixed in v.[1.2.6](https://github.com/fcannizzaro/npm-install/releases/tag/1.2.6)

**Comment by jfilter** [comment]
Thanks for the reply. But all of the modules are currently installed.
