### ISSUE TITLE
This does not work on JSX files, only on JS Files? 

### ISSUE THREAD

**Issue by ianizaguirre** [fcannizzaro/npm-install#5]
Hi, can you please make this package work on files ending in .jsx   , I noticed no NPM symbols show on .jsx files , but when the file is .js the icons show correctly.

**Comment by ianizaguirre** [comment]
Actually,  I was able to figure out how to make npm-install work with jsx files. I submitted a pull request, since people working with ReactJs will find npm-install useful if there files end in .js OR .jsx.

My Pull Request: https://github.com/fcannizzaro/npm-install/pull/6

**Comment by fcannizzaro** [comment]
👍
